/*
 * Copyright 2024 LY Corporation
 *
 * LY Corporation licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */

buildscript {
    ext.kotlin_version = "$project.kotlinVersion"
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.12.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.10"
        classpath "de.mannodermaus.gradle.plugins:android-junit5:1.9.3.0"
    }
}

plugins {
    id "io.github.gradle-nexus.publish-plugin" version "1.3.0"
}

group = "com.linecorp"

// The root project is not published
afterEvaluate {
    tasks.withType(PublishToMavenRepository).configureEach { enabled = false }
}

nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://ossrh-staging-api.central.sonatype.com/service/local/"))
            snapshotRepositoryUrl.set(uri("https://central.sonatype.com/repository/maven-snapshots/"))

            def sonatypeUsername = project.findProperty("sonatypeUsername")
            def sonatypePassword = project.findProperty("sonatypePassword")

            username.set(sonatypeUsername)
            password.set(sonatypePassword)
        }
    }
}
